### ISSUE TITLE
Enhancement Assets Group in vendor/bower

### ISSUE THREAD

**Issue by tecnoterabyte** [digitv/yii2bootstrap4#1]
Hi, excelent extension yii2, it would not be good if you used bower-asset/bootstrap, is exactly the same as using twbs/bootstrap, the difference is that we will have all the common assets under the bower folder,

Regards

**Comment by digitv** [comment]
Hello, I undersdand that this is good aproach, but it confliclts with yiisoft/yii2-bootstrap, which depends on bower-asset/bootstrap ~v3 (not v4), so it cant be upgraded.

**Comment by tecnoterabyte** [comment]
ok, thanks, if you are going to work with bootstrap v4 you do not need bootstrap v3, you will have a big conflict because there are still equal classes,

Regards

**Comment by digitv** [comment]
Yii2 is framework with multiple entrypoints (as in advanced template). So theoretically you can use different CSS-framework on each end point (not simultaneously of course) :)
